version: 0.0
os: linux
files:
  - source: /
    destination: /opt/deployment/dacast
hooks:
  BeforeInstall:
    - location: build/deploy-scripts/before-script.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: build/deploy-scripts/after-script.sh
      timeout: 600
      runas: deploy
